### ISSUE TITLE
Pretty print does not work

### ISSUE THREAD

**Issue by V0XNIHILI** [gustavopch/tsc-files#8] opened 2020-06-03 16:14 UTC
Hi! I really love your work on this tool! I googled my butt of for how to use the `--project` flag with a list of files and came across your tool in a discussion on GitHub.

I however found that if you pass the `--pretty` flag to make sure that the output is colored, nothing much changes. See the screenshot below:

![image](https://user-images.githubusercontent.com/24796206/83660681-66cbe400-a5c5-11ea-9817-4feb1f25b82f.png)

I looked into your source code and saw that you are nicely forwarding the args to `tsc`. So do you have any idea where the ignorance towards the `--pretty` flag is coming from? Do you have an idea how to fix this?

PS: I would like to contribute if you can't find the time :)

**Comment by gustavopch** [comment] 2020-06-11 23:29
Hey @V0XNIHILI. Thank you! I couldn't reproduce your issue, but take a look at the `--pretty` documentation in https://www.typescriptlang.org/docs/handbook/compiler-options.html. It seems it'll be `false` when you're piping to another program or redirecting output to a file. It's probably the default behavior of `tsc` and not something on `tsc-files`'s end.

**Comment by sjungwirth** [comment] 2020-09-23 18:19
I'm having this issue as well; I think there is a bug here https://github.com/gustavopch/tsc-files/blob/744c2aafe3a6861706c96e0b1a9d19106b86caa4/lib/index.js#L17-L20 . It looks like we're trying to remove `-p tsconfig.json` from the args if it exists, but Array.splice returns deleted items, and also the behavior is wrong if -p option doesn't exist in args either.

**Comment by sjungwirth** [comment] 2020-09-23 18:25
changing this section to this fixes the issue for me:
```
const remainingArgsToForward = args
  .slice()
  .filter(arg => !files.includes(arg))

if(~argsProjectIndex) {
  remainingArgsToForward.splice(argsProjectIndex, 2)
}
```

**Comment by gustavopch** [comment] 2021-01-18 13:11
Fixed in https://github.com/gustavopch/tsc-files/releases/tag/v1.1.2
Thanks @sjungwirth

**Closed by gustavopch** 2021-01-18 13:11 UTC
